In [1]:
from census import Census
from us import states
import us
import requests
import zipfile
import io
import geopandas as gpd
import pandas as pd
import os

In [2]:
key = '5984786462aaccc39f904bf750cc8274bd40f9f8'

In [3]:
dict_of_states = {'AK':['02','ALASKA'], 'MS':['28','MISSISSIPPI'],'AL':['01','ALABAMA'], 'MT':['30','MONTANA'],
'AR':['05','ARKANSAS'],'NC':['37','NORTH CAROLINA'], 'AS':['60','AMERICAN SAMOA'],
 'ND':['38','NORTH DAKOTA'], 'AZ':['04','ARIZONA'], 'NE': ['31','NEBRASKA'],
'CA':['06','CALIFORNIA'], 'NH':['33','NEW HAMPSHIRE'], 'CO':['08', 'COLORADO'], 'NJ':['34', 'NEW JERSEY'],
'CT':['09', 'CONNECTICUT'], 'NM':['35', 'NEW MEXICO'],'DC':['11','DISTRICT OF COLUMBIA'], 'NV':['32','NEVADA'],
'DE':['10', 'DELAWARE'], 'NY':['36','NEW YORK'], 'FL':['12','FLORIDA'], 'OH':['39','OHIO'],
'GA':['13','GEORGIA'], 'OK':['40','OKLAHOMA'], 'GU':['66','GUAM'], 'OR':['41','OREGON'],
'HI':['15','HAWAII'],'PA':['42','PENNSYLVANIA'],'IA':['19','IOWA'], 'PR':['72','PUERTO RICO'],
'ID':['16','IDAHO'],'RI':['44','RHODE ISLAND'],'IL':['17','ILLINOIS'],'SC':['45','SOUTH CAROLINA'],
'IN':['18','INDIANA'],'SD':['46','SOUTH DAKOTA'],'KS':['20','KANSAS'],'TN':['47','TENNESSEE'],
'KY':['21','KENTUCKY'],'TX':['48','TEXAS'],'LA':['22','LOUISIANA'],'UT':['49','UTAH'],'MA':['25','MASSACHUSETTS'],
'VA':['51','VIRGINIA'],'MD':['24','MARYLAND'],'VI':['78','VIRGIN ISLANDS'],'ME':['23','MAINE'],
'VT':['50','VERMONT'],'MI':['26','MICHIGAN'],'WA':['53','WASHINGTON'],'MN':['27','MINNESOTA'],'WI':['55','WISCONSIN'],
'MO':['29','MISSOURI'],'WV':['54','WEST VIRGINIA'],'WY': ['56','WYOMING']}

In [4]:
def download_shp_and_save():
    '''
    Creates folders for each state, downloads the shapefile, unzip it and saves it into a folder
    for each state
    '''
    if not os.path.exists('shapefiles/'):
            os.mkdir('shapefiles/')
    for state, state_info in dict_of_states.items():
        if not os.path.exists('shapefiles/' + state_info[1]):
            os.mkdir('shapefiles/' + state_info[1])
        link = 'https://www2.census.gov/geo/tiger/TIGER2010/TABBLOCK/2010/tl_2010_{}_tabblock10.zip'.format(state_info[0])
        print(state_info[1])
        print(link)
        req = requests.get(link)
        file = zipfile.ZipFile(io.BytesIO(req.content))
        file.extractall(path= "./shapefiles/" + state_info[1])

In [5]:
def open_shape(state):
    '''
    Opens a shapefile as a geopandas object
    inputs:
        state(str): valid values are State FIP codes ("AK", "CA", etc)
    returns:
        geopandas dataframe
    '''
    rv = gpd.read_file('shapefiles/' + dict_of_states[state][1] + '/tl_2010_{}_tabblock10.shp'.format(dict_of_states[state][0]))
    return rv

In [101]:
open_shape('AK')

,STATEFP10,COUNTYFP10,TRACTCE10,BLOCKCE10,GEOID10,NAME10,MTFCC10,UR10,UACE10,UATYP10,FUNCSTAT10,ALAND10,AWATER10,INTPTLAT10,INTPTLON10,geometry
0,02,013,000100,2132,020130001002132,Block 2132,G5040,R,None,None,S,0,1140917,+56.0119409,-161.0036526,"POLYGON ((-161.00640 56.00869, -161.00668 56.0..."
1,02,013,000100,1015,020130001001015,Block 1015,G5040,R,None,None,S,0,97223,+55.2463629,-162.9248666,"POLYGON ((-162.92847 55.24522, -162.92846 55.2..."
2,02,013,000100,1276,020130001001276,Block 1276,G5040,R,None,None,S,0,75011,+55.2331988,-162.9080366,"POLYGON ((-162.91138 55.23385, -162.91028 55.2..."
3,02,013,000100,2165,020130001002165,Block 2165,G5040,R,None,None,S,0,1315769,+55.7739080,-161.7877456,"POLYGON ((-161.76931 55.78114, -161.77470 55.7..."
4,02,013,000100,1120,020130001001120,Block 1120,G5040,R,None,None,S,0,647915,+54.6743103,-164.4056094,"POLYGON ((-164.39607 54.67081, -164.39744 54.6..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45287,02,290,000200,1533,022900002001533,Block 1533,G5040,R,None,None,S,192374,0,+65.1942321,-149.4203145,"POLYGON ((-149.42252 65.19636, -149.42077 65.1..."
45288,02,290,000200,2027,022900002002027,Block 2027,G5040,R,None,None,S,96531,0,+65.4337574,-149.6900337,"POLYGON ((-149.68435 65.43928, -149.68404 65.4..."
45289,02,290,000200,2194,022900002002194,Block 2194,G5040,R,None,None,S,145545921,0,+65.0354771,-148.9522668,"POLYGON ((-148.67494 64.98043, -148.67610 64.9..."
45290,02,290,000200,1200,022900002001200,Block 1200,G5040,R,None,None,S,9871,0,+66.9069849,-151.5232479,"POLYGON ((-151.52428 66.90763, -151.52358 66.9..."
45291,02,290,000300,3068,022900003003068,Block 3068,G5040,R,None,None,S,23771,0,+64.3251847,-158.7269695,"POLYGON ((-158.72532 64.32446, -158.72605 64.3..."